name: EkoMurvica
description: Aplikacija za Eko Murvicu

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 "

dependencies:
  flutter:
    sdk: flutter

  url_launcher: 
  flutter_svg: ^0.18.0 
  animated_text_kit: 
  intl: 
  flutter_calendar_carousel: 
  image_picker: 
 # google_maps_flutter: ^0.5.19+2
  http: 
  redux: 
  flutter_redux: 
#  webview_flutter: ^0.3.10+3
  firebase_core: 
  firebase_analytics: 
  firebase_messaging: 
  image: 
  shared_preferences: 
  webview_flutter: 
  flutter_webview_plugin:
  
  
  # google_maps_flutter: ^0.0.3+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "images/ikona.png"
#  image_path_android: "assets/images/icon-710x599-android.png"
#  image_path_ios: "assets/images/icon-710x599-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - images/Smetlari.jpeg
  - images/o-nama.jpg
  - images/cistoca-logo.gif
  - images/cut.png
  - images/chat.png
  - images/text-prvi-screen.png
  - images/text-prvi-screen.svg
  - images/logo.png
  - images/maskota.svg
  - images/test.svg
  - images/oblak-prazan.svg
  - oblak-prazan-test.png
  - images/maskota.png
  - images/chat-dark.png
  - images/maskota.svg
  - images/maskota-test.png
  - images/maskota-izpricava.svg
  - images/maskota-ljut.svg
  - images/maskota-neutralno.svg
  - images/maskota-nogomet-odjeca.svg
  - images/maskota-nogomet-odjeca.png
  - images/maskota-parking.svg
  - images/maskota-placa-odjeca.svg
  - images/maskota-placa-odjeca.png
  - images/maskota-razmislja.svg
  - images/maskota-razmislja-2.svg
  - images/maskota-smetlar.svg
  - images/maskota-smetlar.png
  - images/image-placeholder.png
  - images/maskota-ljut.png
  - images/maskota-razmislja.png
  - images/oblak-prazan.png
  - images/maskota-parking.png
  - assets/ulice.json
  - images/ikona.png
  - images/recikliranje.png
  - images/viber.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
